# Form implementation generated from reading ui file 'setupUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1107, 580)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("background-color: rgb(30, 31, 34);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_menu_layout = QtWidgets.QFrame(parent=self.centralwidget)
        self.top_menu_layout.setMinimumSize(QtCore.QSize(0, 26))
        self.top_menu_layout.setMaximumSize(QtCore.QSize(16777215, 26))
        self.top_menu_layout.setStyleSheet("QFrame {\n"
"    background-color: rgb(43, 45, 48);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.top_menu_layout.setObjectName("top_menu_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_menu_layout)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.top_menu_layout)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setStyleSheet("margin-left: 18px;\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.head_hide = QtWidgets.QPushButton(parent=self.top_menu_layout)
        self.head_hide.setMinimumSize(QtCore.QSize(26, 26))
        self.head_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.head_hide.setStyleSheet("")
        self.head_hide.setObjectName("head_hide")
        self.horizontalLayout_3.addWidget(self.head_hide)
        self.head_resize = QtWidgets.QPushButton(parent=self.top_menu_layout)
        self.head_resize.setMinimumSize(QtCore.QSize(26, 26))
        self.head_resize.setMaximumSize(QtCore.QSize(26, 26))
        self.head_resize.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.head_resize.setObjectName("head_resize")
        self.horizontalLayout_3.addWidget(self.head_resize)
        self.head_exit = QtWidgets.QPushButton(parent=self.top_menu_layout)
        self.head_exit.setMinimumSize(QtCore.QSize(26, 26))
        self.head_exit.setMaximumSize(QtCore.QSize(26, 26))
        self.head_exit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.head_exit.setObjectName("head_exit")
        self.horizontalLayout_3.addWidget(self.head_exit)
        self.verticalLayout.addWidget(self.top_menu_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_layout_bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.left_layout_bar.setMinimumSize(QtCore.QSize(40, 0))
        self.left_layout_bar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.left_layout_bar.setStyleSheet("QFrame#left_layout_bar {\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-top: 2px solid rgb(30, 31, 34);\n"
"    border-right: 2px solid rgb(30, 31, 34);\n"
"    border-bottom: 2px solid rgb(30, 31, 34);\n"
"}")
        self.left_layout_bar.setObjectName("left_layout_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_layout_bar)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.left_layout_bar)
        self.WorkLayout = QtWidgets.QVBoxLayout()
        self.WorkLayout.setContentsMargins(-1, 0, 1, -1)
        self.WorkLayout.setSpacing(0)
        self.WorkLayout.setObjectName("WorkLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ScriptLists = QtWidgets.QListView(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ScriptLists.sizePolicy().hasHeightForWidth())
        self.ScriptLists.setSizePolicy(sizePolicy)
        self.ScriptLists.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ScriptLists.setStyleSheet("QListView#ScriptLists {\n"
"    border: none;\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-top: 2px solid rgb(30, 31, 34);\n"
"    border-bottom: 2px solid rgb(30, 31, 34);\n"
"   }")
        self.ScriptLists.setObjectName("ScriptLists")
        self.horizontalLayout_4.addWidget(self.ScriptLists)
        self.ScriptEditorLayout = QtWidgets.QVBoxLayout()
        self.ScriptEditorLayout.setContentsMargins(-1, 0, -1, 1)
        self.ScriptEditorLayout.setSpacing(0)
        self.ScriptEditorLayout.setObjectName("ScriptEditorLayout")
        self.ScriptEditorTop = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScriptEditorTop.sizePolicy().hasHeightForWidth())
        self.ScriptEditorTop.setSizePolicy(sizePolicy)
        self.ScriptEditorTop.setMinimumSize(QtCore.QSize(0, 39))
        self.ScriptEditorTop.setMaximumSize(QtCore.QSize(16777215, 39))
        self.ScriptEditorTop.setStyleSheet("QFrame#ScriptEditorBar_2 {\n"
"    background-color: rgb(30, 31, 34);\n"
"    border-bottom: 1px solid rgb(57, 59, 64);\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.ScriptEditorTop.setObjectName("ScriptEditorTop")
        self.ScriptEditorBar = QtWidgets.QHBoxLayout(self.ScriptEditorTop)
        self.ScriptEditorBar.setObjectName("ScriptEditorBar")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.ScriptEditorBar.addItem(spacerItem1)
        self.ScriptRunButt = QtWidgets.QPushButton(parent=self.ScriptEditorTop)
        self.ScriptRunButt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/assets/Run.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ScriptRunButt.setIcon(icon)
        self.ScriptRunButt.setObjectName("ScriptRunButt")
        self.ScriptEditorBar.addWidget(self.ScriptRunButt)
        self.ScriptRunRepeatButt = QtWidgets.QPushButton(parent=self.ScriptEditorTop)
        self.ScriptRunRepeatButt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/assets/RunRepeat.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ScriptRunRepeatButt.setIcon(icon1)
        self.ScriptRunRepeatButt.setObjectName("ScriptRunRepeatButt")
        self.ScriptEditorBar.addWidget(self.ScriptRunRepeatButt)
        spacerItem2 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.ScriptEditorBar.addItem(spacerItem2)
        self.ScriptEditorLayout.addWidget(self.ScriptEditorTop)
        self.ScriptEditor = QtWidgets.QTextBrowser(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.ScriptEditor.sizePolicy().hasHeightForWidth())
        self.ScriptEditor.setSizePolicy(sizePolicy)
        self.ScriptEditor.setStyleSheet("QTextBrowser {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(57, 59, 64);\n"
"   }")
        self.ScriptEditor.setObjectName("ScriptEditor")
        self.ScriptEditorLayout.addWidget(self.ScriptEditor)
        self.ScriptEditorBottom = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScriptEditorBottom.sizePolicy().hasHeightForWidth())
        self.ScriptEditorBottom.setSizePolicy(sizePolicy)
        self.ScriptEditorBottom.setMinimumSize(QtCore.QSize(0, 24))
        self.ScriptEditorBottom.setMaximumSize(QtCore.QSize(16777215, 24))
        self.ScriptEditorBottom.setStyleSheet("margin-left: 5px;\n"
"color: rgb(157, 160, 168);")
        self.ScriptEditorBottom.setObjectName("ScriptEditorBottom")
        self.ScriptEditorLayout.addWidget(self.ScriptEditorBottom)
        self.horizontalLayout_4.addLayout(self.ScriptEditorLayout)
        self.WorkLayout.addLayout(self.horizontalLayout_4)
        self.TerminalLayout = QtWidgets.QVBoxLayout()
        self.TerminalLayout.setSpacing(0)
        self.TerminalLayout.setObjectName("TerminalLayout")
        self.horizontalFrame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.horizontalFrame_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 34))
        self.horizontalFrame_3.setStyleSheet("background-color: rgb(43, 45, 48);")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.TerminalFrame_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.TerminalFrame_2.setObjectName("TerminalFrame_2")
        self.TerminalLayout.addWidget(self.horizontalFrame_3)
        self.TerminalText_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TerminalText_2.sizePolicy().hasHeightForWidth())
        self.TerminalText_2.setSizePolicy(sizePolicy)
        self.TerminalText_2.setMaximumSize(QtCore.QSize(16777215, 806))
        self.TerminalText_2.setStyleSheet("QTextBrowser {\n"
"       border: none;\n"
"   }")
        self.TerminalText_2.setObjectName("TerminalText_2")
        self.TerminalLayout.addWidget(self.TerminalText_2)
        self.WorkLayout.addLayout(self.TerminalLayout)
        self.horizontalLayout.addLayout(self.WorkLayout)
        self.verticalFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.verticalFrame.setMinimumSize(QtCore.QSize(40, 0))
        self.verticalFrame.setMaximumSize(QtCore.QSize(40, 16777215))
        self.verticalFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-bottom: 2px solid rgb(30, 31, 34);\n"
"}")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 29))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 29))
        self.frame_2.setStyleSheet("background-color: rgb(43, 45, 48);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " GInputAI"))
        self.head_hide.setText(_translate("MainWindow", "—"))
        self.head_resize.setText(_translate("MainWindow", "▭"))
        self.head_exit.setText(_translate("MainWindow", "x"))
        self.ScriptEditorBottom.setText(_translate("MainWindow", "MainWindow > __profile_dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
